### PR TITLE
Change AGP and ddmlib to compileOnly instead of implementation

### LINKED ISSUE #95: Cannot use plugin 1.5.0 with AGP 3.4
We currently use AGP 3.4.2 and cannot update to 3.5.0 because DexGuard doesn't support it yet.  
When we apply OkReplay 1.5.0 it pulls AGP 3.5.0 since that's an implementation dependency of OkReplay plugin and our build fails with a message like:
```
DexGuard Gradle plugin: Android Gradle plugin version is not supported. (3.5.0), supported versions include [2.3.0:3.4.*].
```
To avoid this I think we should change AGP dependency from `implementation` to `compileOnly`. I'm working on a fix right now.

### PR DESCRIPTION
**Pull request by technoir42**
This is to avoid pulling a higher version of AGP or ddmlib when OkReplay plugin is applied.  
I had to change how plugin classpath is provided to tests since the default one supplied by `withPluginClasspath()` no longer has AGP in it.
Fixes #95 

Note that this PR is based on #94.

### CODE REVIEW

**Comment by felipecsl** [comment]
I don't think this would work since there are breaking changes to the internal AGP APIs that we rely on for version 3.5.0, so moving to `compileOnly` wouldn't help as it would crash in runtime.

**Comment by technoir42** [comment]
@felipecsl I'm able to build this locally with AGP 3.4.2 and even 3.3.2 and all the tests pass.

**Comment by felipecsl** [comment]
hmmm thats surprising since #89 reports exactly the opposite if I understand correctly

**Comment by technoir42** [comment]
`BaseExtension.adbExecutable` that you switched to in da2789cc6590a716c469ccee3a801b83802f22a3 seems to have been available for a while according to [this](https://google.github.io/android-gradle-dsl/3.0/com.android.build.gradle.AppExtension.html). So the plugin is now compatible with AGP 3.5 and old versions of AGP too.

**Comment by felipecsl** [comment]
oohhh it's a backwards compatible change then 👍 fantastic, thanks for digging!

**Pull request merged**
